title: マイクラサーバーの知識どころ - onudonLabo
email: onudonlabo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  マイクラサーバーの知識どころ。spigot plugin, Minecraft serverなどの情報を発信しております。
baseurl: "/"
url: "https://onudonlabo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: onudonLabo
github_username:  onudonlabo

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag